spring.application.name=weather

# === STOMP 설정 ===
io.u2ware.common.stomp.url=ws://localhost:9030/stomp
io.u2ware.common.stomp.subscriptions.weather=/topic/weather
io.u2ware.common.stomp.subscriptions.sessions=/topic/sessions

# === 날씨 관련 설정 ===
weather.api.key=433ba902b7082d331c980a4f551daaa6
weather.api.base.url=http://api.openweathermap.org/data/2.5/weather
weather.api.fixed.url=https://api.openweathermap.org/data/2.5/weather?q=Seoul&lang=kr&units=metric&appid=433ba902b7082d331c980a4f551daaa6

# === 로깅 레벨 설정 ===
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.exception-conversion-word=%ex{short}
logging.level.org.springframework.jdbc.datasource.init=WARN
logging.level.org.springframework.web.socket.sockjs=OFF

logging.file.name=var/lib/examples/logs/boilerplate-backend.log
logging.logback.rollingpolicy.max-file-size=1GB
logging.logback.rollingpolicy.file-name-pattern=var/lib/examples/logs/boilerplate-backend-%d{yyyy-MM-dd}.%i.log