spring.application.name=weather

# === 로깅 레벨 설정 ===
# 애플리케이션 전체 기본 로그 레벨을 INFO로 설정합니다.
logging.level.root=INFO
# Hibernate가 출력하는 SQL을 INFO 레벨로 기록합니다.
logging.level.org.hibernate.SQL=INFO
# 바인딩(파라미터) 로그를 TRACE로 기록합니다. (자세한 파라미터 값 확인용)
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# 애플리케이션 예외 로그를 간결하게 출력하도록 설정합니다. (stack trace 대신 간단한 메시지만 출력)
# logging.exception-conversion-word=%ex{short}

# === STOMP 설정 ===
io.u2ware.common.stomp.url=ws://localhost:9030/stomp
io.u2ware.common.stomp.subscriptions.weather=/topic/weather